# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 16:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictures', '0008_auto_20190325_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='picture_Main_pic',
            field=models.ImageField(blank=True, upload_to='instagram/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
