# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0010_auto_20190325_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='caption',
            field=models.CharField(default=6, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='comments',
            field=models.CharField(default=9, max_length=60),
            preserve_default=False,
        ),
    ]
