# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0011_auto_20190326_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
