# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_moringamerch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoringaMerch',
        ),
    ]
